# Generated by Django 3.1.2 on 2021-04-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prénom', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('tel', models.IntegerField()),
                ('departement', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=255)),
                ('date_de_declaration', models.DateTimeField(auto_now_add=True)),
                ('TestCovid', models.FileField(upload_to='')),
                ('sujet', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
