# Generated by Django 3.1.2 on 2021-05-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210509_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listes',
            name='departement',
            field=models.CharField(blank=True, choices=[('1', 'MIAGE'), ('2', 'ECONOMIE')], default='1', help_text='chosir votre departement', max_length=1),
        ),
    ]
