# Generated by Django 3.1.2 on 2021-05-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210509_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listes',
            name='departement',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='listes',
            name='promotion',
            field=models.CharField(max_length=255),
        ),
    ]
