# Generated by Django 3.1.2 on 2021-05-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_listes_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listes',
            name='num',
        ),
        migrations.AlterField(
            model_name='listes',
            name='promotion',
            field=models.CharField(choices=[('01', 'Licence1'), ('01', 'Licence2'), ('01', 'Licence3'), ('01', 'Master1'), ('01', 'Master2')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='listes',
            name='statut',
            field=models.CharField(choices=[('01', 'étudiant'), ('02', 'enseignant')], default='01', max_length=2),
        ),
    ]
