# Generated by Django 3.1.2 on 2021-05-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210509_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listes',
            name='sujet',
            field=models.CharField(choices=[('01', 'positif'), ('02', 'cas contact'), ('03', 'symptomatique'), ('04', 'autres')], default='01', max_length=2),
        ),
    ]
