# Generated by Django 3.1.2 on 2021-05-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210509_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listes',
            name='departement',
            field=models.CharField(choices=[('01', 'MIASHS'), ('02', 'ECONOMIE_GESTION')], default='01', max_length=2),
        ),
    ]
