# Generated by Django 3.1.2 on 2021-05-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210509_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listes',
            name='departement',
            field=models.CharField(choices=[('MIASHS', 'MIASHS'), ('ECONOMIE ET GESTION', 'ECONOMIE_GESTION')], default='MIASHS', max_length=255),
        ),
        migrations.AlterField(
            model_name='listes',
            name='promotion',
            field=models.CharField(choices=[('L1', 'Licence1'), ('L2', 'Licence2'), ('L3', 'Licence3'), ('M1', 'Master1'), ('M1', 'Master2')], default='L1', max_length=2),
        ),
    ]
