# Generated by Django 3.1.2 on 2021-05-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210509_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listes',
            name='statut',
            field=models.CharField(choices=[('Etudiant', 'Etudiant'), ('Enseignant', 'Enseignant')], default='Etudiant', max_length=255),
        ),
    ]
