# Generated by Django 3.1.2 on 2021-05-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210509_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listes',
            name='sujet',
            field=models.CharField(choices=[('Positif', 'Positif'), ('Négatif', 'Cas contact'), ('Syptomatique', 'Symptomatique'), ('Autres', 'Autres')], default='Positif', max_length=255),
        ),
    ]
