# Generated by Django 3.1.2 on 2021-05-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210509_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listes',
            old_name='tel',
            new_name='telephone',
        ),
        migrations.AlterField(
            model_name='listes',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
