# Generated by Django 3.1.2 on 2021-05-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20210510_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listes',
            old_name='TestCovid',
            new_name='testPCR',
        ),
    ]
