# Generated by Django 3.1.2 on 2021-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210510_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listes',
            old_name='promotion',
            new_name='niveau',
        ),
        migrations.AddField(
            model_name='listes',
            name='groupe_de_TD',
            field=models.CharField(choices=[('TD1', 'TD1'), ('TD2', 'TD2'), ('TD3', 'TD3')], default='TD1', max_length=255),
        ),
    ]
