# Generated by Django 3.1.2 on 2021-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20210511_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='listes',
            name='parcour',
            field=models.CharField(choices=[('MIAGE', 'MIAGE'), ('MATHS', 'MATHS'), ('ECONOMIE', 'ECONOMIE'), ('GESTION', 'GESTION')], default='MIAGE', max_length=255),
        ),
    ]
