# Generated by Django 3.1.2 on 2021-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_listes_parcour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listes',
            name='parcour',
        ),
        migrations.AddField(
            model_name='listes',
            name='parcours',
            field=models.CharField(choices=[('MIAGE', 'MIAGE'), ('MATHS', 'MATHS'), ('ECONOMIE', 'ECONOMIE'), ('GESTION', 'GESTION'), ('DOUBLE_LICENCE', 'DOUBLE_LICENCE')], default='MIAGE', max_length=255),
        ),
    ]
