# Generated by Django 3.1.2 on 2021-05-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20210515_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listes',
            name='département',
            field=models.CharField(choices=[('MIASHS', 'MIASHS'), ('Economie et Gestion', 'Economie et Gestion'), ('Espagnol', 'Espagnol'), ('Etudes anglo américaines', 'Etudes anglo américaines'), ('Etudes germaniques', 'Etudes germaniques'), ('Italien ', 'Italien '), (' Langues étrangères appliquées (LEA)', ' Langues étrangères appliquées (LEA)'), ('Portugais', 'Portugais'), ('Russe', 'Russe'), ('CRL - Centre de ressources Langues', 'CRL - Centre de ressources Langues'), ('Arts du spectacle', 'Arts du spectacle'), ("Sciences de l'information et de la communication", "Sciences de l'information et de la communication"), ('Langues et littératures grecques et latines ', 'Langues et littératures grecques et latines'), ('Lettres modernes ', 'Lettres modernes'), ('hilosophie', 'hilosophie'), ('Sciences du langage', 'Sciences du langage'), ('Science Politique ', 'Science Politique'), (' Psychologie', ' Psychologie'), (" Sciences de l'éducation", " Sciences de l'éducation"), ('Administration économique et sociale', 'Administration économique et sociale'), ('Anthropologie', 'Anthropologie'), ('Histoire', 'Histoire'), ("Histoire de l'art et de l'archéologie", "Histoire de l'art et de l'archéologie"), ('Géographie et aménagement', 'Géographie et aménagement'), ('Sociologie', 'Sociologie'), ("Métiers du livre et de l'audiovisuel", "Métiers du livre et de l'audiovisuel"), ("Sciences de l'ingénieur", "Sciences de l'ingénieur"), ('Génie Électrique & Informatique Industrielle (GEII)', 'Génie Électrique & Informatique Industrielle (GEII)'), ('Génie Mécanique & Productique (GMP)', 'Génie Mécanique & Productique (GMP)'), ('Génie Thermique & Énergie (GTE)', 'Génie Thermique & Énergie (GTE)'), ('Gestion des Entreprises & des Administrations', 'Gestion des Entreprises & des Administrations'), ('Carrières Sociales', 'Carrières Sociales'), ("Métiers du livre et de l'audiovisuel", "Métiers du livre et de l'audiovisuel")], default='MIASHS', max_length=255),
        ),
    ]
