# Generated by Django 3.1.2 on 2021-05-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20210515_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listes',
            name='parcours',
            field=models.CharField(choices=[('MIAGE', 'MIAGE'), ('MATHS', 'MATHS'), ('ECONOMIE', 'ECONOMIE'), ('GESTION', 'GESTION'), ('DOUBLE LICENCE', 'DOUBLE LICENCE'), ('AUTRE PARCOUR', 'AUTRE PARCOUR')], default='MIAGE', max_length=255),
        ),
    ]
